[2024-08-26 15:21:41,347: INFO: stage1: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-26 15:21:41,348: ERROR: stage1: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "stage1.py", line 27, in <module>
    obj.main()
  File "stage1.py", line 14, in main
    config = ConfigurationManager()
  File "c:\users\akherchouche\end_to_end_project_mlfow_and_dvc\src\binary_classifier\config\configuration.py", line 14, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\akherchouche\AppData\Local\anaconda3\envs\cancer\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\akherchouche\end_to_end_project_mlfow_and_dvc\src\binary_classifier\utils\common.py", line 37, in read_yaml
    raise e
  File "c:\users\akherchouche\end_to_end_project_mlfow_and_dvc\src\binary_classifier\utils\common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
